### ISSUE TITLE
Broken minimap markers with UI scaling?

### ISSUE THREAD

**Issue by Grammernatzi** [Ved-s/MapMarkers#2]
I play at 1440p, so I have to scale the UI up to 150%, otherwise it's really tiny. When I do so, the minimap markers end up in the middle of the screen, instead of in the, well, minimap. Is there any potential way to fix this?

**Comment by Ved-s** [comment]
Is this bug on 1.3 or 1.4 Terraria version?
Edit: Bug exists on 1.3

**Comment by Grammernatzi** [comment]
This is on the 1.3 version. I've not messed with 1.4 much with mods yet.

**Comment by Ved-s** [comment]
Fixed in 1.4.1

**Comment by Grammernatzi** [comment]
Thank you! And, thank you for the great work on the mod overall
