### ISSUE TITLE
Multiplayer Marker Limit

### ISSUE THREAD

**Issue by creeperwithrabies** [Ved-s/MapMarkers#3]
Hi, apologies if I am being dense, but the files mention that the multiplayer marker limit of 5 can be changed via the mod's console command, I was just wondering how to go about this?

**Comment by Ved-s** [comment]
The command is `mapmarkers limit <limit>` in server console, it is visible in `help` command

**Comment by creeperwithrabies** [comment]
Is there a way of doing it outside of console, since you cannot access the server console if running the server via Steam, and the in game chat console is not showing that command when using the help command, and the command won't run

**Comment by Ved-s** [comment]
Currently no
